### PR TITLE
V4.3 rc5 patches for xpad, ps3 remote

### PR DESCRIPTION
**Pull request by MrChromebox**

### CODE REVIEW

**Comment by fritsch** [comment]
thx much @lrusak ping for openelec-next

Only missing the DVB stuff by @stefansaraev :-) no hurry

**Comment by stefansaraev** [comment]
when the time comes. feel free to drop octopus /me runs

**Comment by fritsch** [comment]
This is not an option :-) - but 4.3 is needed or Braswell will suck. OE 6.0
will realize that immediately.

2015-10-18 23:15 GMT+02:00 Stefan Saraev notifications@github.com:

> when the time comes. feel free to drop octopus /me runs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fritsch/OpenELEC.tv/pull/1#issuecomment-149048062.

## 

```
               Key-ID:     0x1A995A9B
               keyserver: pgp.mit.edu
```

# 

Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment]
And Braswell is the only chip that can do HEVC currently that is affordable ... though also not with OE mainline  .... but with jarvis out of the box.

**Pull request merged**
